import logging
import unittest

from nion.utils import Color


class TestColorClass(unittest.TestCase):
    def setUp(self) -> None:
        pass

    def tearDown(self) -> None:
        pass

    def test_hex_color_init(self):
        ...

    def test_named_color_init(self):
        ...

    def test_transparent_init(self):
        ...

    def test_rgb_init(self):
        ...

    def test_legacy_rgb_init(self):
        ...

    def test_rgba_init(self):
        ...

    def test_legacy_rgba_init(self):
        ...

    def test_unknown_init(self):
        ...

    def test_stored_color(self):
        ...

    def test_hex_color_type(self):
        ...

    def test_named_color_type(self):
        ...

    def test_transparent_type(self):
        ...

    def test_rgb_type(self):
        ...

    def test_legacy_rgb_type(self):
        ...

    def test_rgba_type(self):
        ...

    def test_legacy_rgba_type(self):
        ...

    def test_unknown_type(self):
        ...

    def test_hex_color_params(self):
        ...

    def test_named_color_params(self):
        ...

    def test_transparent_params(self):
        ...

    def test_rgb_params(self):
        ...

    def test_legacy_rgb_params(self):
        ...

    def test_rgba_params(self):
        ...

    def test_legacy_rgba_params(self):
        ...

    def test_unknown_params(self):
        ...

    def test_hex_color_func(self):
        ...

    def test_named_color_func(self):
        ...

    def test_transparent_func(self):
        ...

    def test_rgb_func(self):
        ...

    def test_legacy_rgb_func(self):
        ...

    def test_rgba_func(self):
        ...

    def test_legacy_rgba_func(self):
        ...

    def test_unknown_func(self):
        ...

    def test_hex_color_valid(self):
        ...

    def test_named_color_valid(self):
        ...

    def test_transparent_valid(self):
        ...

    def test_rgb_valid(self):
        ...

    def test_legacy_rgb_valid(self):
        ...

    def test_rgba_valid(self):
        ...

    def test_legacy_rgba_valid(self):
        ...

    def test_unknown_valid(self):
        ...

    def test_hex_color_to_hex(self):
        ...

    def test_named_color_to_hex(self):
        ...

    def test_transparent_to_hex(self):
        ...

    def test_rgb_to_hex(self):
        ...

    def test_legacy_rgb_to_hex(self):
        ...

    def test_rgba_to_hex(self):
        ...

    def test_legacy_rgba_to_hex(self):
        ...

    def test_unknown_to_hex(self):
        ...

    def test_hex_color_expand(self):
        ...

    def test_named_color_expand(self):
        ...

    def test_transparent_expand(self):
        ...

    def test_rgb_expand(self):
        ...

    def test_legacy_rgb_expand(self):
        ...

    def test_rgba_expand(self):
        ...

    def test_legacy_rgba_expand(self):
        ...

    def test_unknown_expand(self):
        ...

    def test_hex_color_alpha(self):
        ...

    def test_named_color_alpha(self):
        ...

    def test_transparent_alpha(self):
        ...

    def test_rgb_alpha(self):
        ...

    def test_legacy_rgb_alpha(self):
        ...

    def test_rgba_alpha(self):
        ...

    def test_legacy_rgba_alpha(self):
        ...

    def test_unknown_alpha(self):
        ...

    def test_equality(self):
        ...

    def test_str(self):
        ...

    def test_repr(self):
        ...